name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main
      - develop # todo delete it

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
    - name: Sync S3 Bucket
      run: |
        aws s3 sync ./ s3://rent-husband --recursive --cache-control no-cache

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DIST_ID }} --paths "/*"
      
